[package]
name = "cp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_derive = "0.1.7"
enum_derive = "0.1.7"
serde = { version = "1.0.162", features = ["derive"] }
