---
name: tarpaulin
on:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.22.0'
          args: '--all-features  -- --test-threads 1'
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true